//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database_FYPEntities : DbContext
    {
        public Database_FYPEntities()
            : base("name=Database_FYPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abortion> Abortions { get; set; }
        public virtual DbSet<Apple_vs_FBI_case> Apple_vs_FBI_cases { get; set; }
        public virtual DbSet<Hunting> Huntings { get; set; }
        public virtual DbSet<UK_better_of_outside_the_EU> UK_better_of_outside_the_EUs { get; set; }
    }
}
